version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  #######################################
  # Challenge: The Challenge microservice
  #######################################
  challenge:
    build:
      context: ./Fitness-Freak/challenge
      dockerfile: challenge.Dockerfile
    image: daniilzam/challenge:project
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/challenge
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
  ####################################
  # Fitness: The Fitness microservice
  ####################################
  fitness:
    build:
      context: ./Fitness-Freak/fitnessassessment
      dockerfile: fitness.Dockerfile
    image: daniilzam/fitness:project
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
  ####################################
  # Product: The Product microservice
  ####################################
  product:
    build:
      context: ./Fitness-Freak/product
      dockerfile: product.Dockerfile
    image: daniilzam/product:project
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/product
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"