version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  #######################################
  # Challenge: The Challenge microservice
  #######################################
  challenge:
    build:
      context: ./challenge
      dockerfile: challenge.Dockerfile
    image: daniilzam/challenge:project
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/challenge
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
  ####################################
  # Fitness: The Fitness microservice
  ####################################
  # fitness:
  #   build:
  #     context: ./Fitness-Freak/fitnessassessment
  #     dockerfile: fitness.Dockerfile
  #   image: daniilzam/fitness:project
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5001:5001"
  #############################
  # User: The User microservice
  #############################
  # user:
  #   build:
  #     context: ./user
  #     dockerfile: user.Dockerfile
  #   image: daniilzam/user:project
  #   restart: always
  #   environment:
  #     GOOGLE_APPLICATION_CREDENTIALS: ./user/serviceAccountKey.json
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5003:5003"
  ####################################
  # Product: The Product microservice
  ####################################
  product:
    build:
      context: ./product
      dockerfile: product.Dockerfile
    image: daniilzam/product:project
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/product
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"
  ########################################
  # Verification: The Product microservice
  ########################################
  # verification:
  #   build:
  #     context: ./verification
  #     dockerfile: verification.Dockerfile
  #   image: daniilzam/verification:project
  #   restart: always
  #   environment:
  #     dbURL: 
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5006:5006"